# Generated by Django 3.2.7 on 2021-09-26 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('album_title', models.CharField(max_length=500)),
                ('album_logo', models.FileField(default='settings.MEDIA_ROOT/album/default.png', upload_to='album')),
            ],
        ),
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('thumbnail', models.ImageField(default='settings.MEDIA_ROOT/artist/default.png', upload_to='artist')),
                ('bio', models.TextField(blank=True, null=True, verbose_name='Artist Bio')),
                ('country', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('track_title', models.CharField(max_length=250)),
                ('audio_file', models.FileField(default='settings.MEDIA_ROOT/track/default.png', upload_to='track')),
                ('album', models.ForeignKey(on_delete=models.SET('Independent Track'), to='api.album')),
            ],
        ),
        migrations.AddField(
            model_name='album',
            name='artist',
            field=models.ForeignKey(on_delete=models.SET('Anonymous'), to='api.artist'),
        ),
    ]
