# Generated by Django 3.2.7 on 2021-09-26 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210926_0903'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='album_logo',
            field=models.FileField(default='settings.MEDIA_ROOT/default.png', upload_to='album'),
        ),
        migrations.AlterField(
            model_name='artist',
            name='thumbnail',
            field=models.ImageField(default='settings.MEDIA_ROOT/default.png', upload_to='artist'),
        ),
        migrations.AlterField(
            model_name='track',
            name='audio_file',
            field=models.FileField(default='settings.MEDIA_ROOT/default.png', upload_to='track'),
        ),
    ]
